<?php
/**
 * ArrayOfSymbolsInnerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  D4T\MT5Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metatrader 5 Rest Api
 *
 * MetaTrader microservice. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: mikha.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace D4T\MT5Sdk;

/**
 * ArrayOfSymbolsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ArrayOfSymbolsInner
 * @package     D4T\MT5Sdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArrayOfSymbolsInnerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArrayOfSymbolsInner"
     */
    public function testArrayOfSymbolsInner()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {
    }

    /**
     * Test attribute "currency_base"
     */
    public function testPropertyCurrencyBase()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "spread"
     */
    public function testPropertySpread()
    {
    }

    /**
     * Test attribute "swap_mode"
     */
    public function testPropertySwapMode()
    {
    }

    /**
     * Test attribute "swap_long"
     */
    public function testPropertySwapLong()
    {
    }

    /**
     * Test attribute "swap_short"
     */
    public function testPropertySwapShort()
    {
    }

    /**
     * Test attribute "vol_min"
     */
    public function testPropertyVolMin()
    {
    }

    /**
     * Test attribute "vol_max"
     */
    public function testPropertyVolMax()
    {
    }

    /**
     * Test attribute "vol_limit"
     */
    public function testPropertyVolLimit()
    {
    }

    /**
     * Test attribute "vol_step"
     */
    public function testPropertyVolStep()
    {
    }

    /**
     * Test attribute "tick_value"
     */
    public function testPropertyTickValue()
    {
    }

    /**
     * Test attribute "tick_size"
     */
    public function testPropertyTickSize()
    {
    }

    /**
     * Test attribute "contract_size"
     */
    public function testPropertyContractSize()
    {
    }

    /**
     * Test attribute "calc_mode"
     */
    public function testPropertyCalcMode()
    {
    }
}
