<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  D4T\MT5Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metatrader 5 Rest Api
 *
 * MetaTrader5 Rest Api. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 0.0.3-oas3
 * Contact: mikha.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace D4T\MT5Sdk;

use D4T\MT5Sdk\Configuration;
use D4T\MT5Sdk\ApiException;
use D4T\MT5Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  D4T\MT5Sdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for updateUser
     *
     * Update user.
     *
     */
    public function testUpdateUser()
    {
    }

    /**
     * Test case for userAddPost
     *
     * Create user.
     *
     */
    public function testUserAddPost()
    {
    }

    /**
     * Test case for userDepositPost
     *
     * Deposit account.
     *
     */
    public function testUserDepositPost()
    {
    }

    /**
     * Test case for userResetPwdPost
     *
     * Reset password.
     *
     */
    public function testUserResetPwdPost()
    {
    }

    /**
     * Test case for userUserLoginDelete
     *
     * Delete user.
     *
     */
    public function testUserUserLoginDelete()
    {
    }

    /**
     * Test case for userUserLoginGet
     *
     * Get user by user login.
     *
     */
    public function testUserUserLoginGet()
    {
    }

    /**
     * Test case for userWithdrawPost
     *
     * Withdraw account.
     *
     */
    public function testUserWithdrawPost()
    {
    }

    /**
     * Test case for usersGroupGet
     *
     * Get list of users.
     *
     */
    public function testUsersGroupGet()
    {
    }
}
