<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  D4T
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metatrader 5 Rest Api
 *
 * MetaTrader microservice. Call /init/ to get token, which is required in other methods.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: mikha.dev@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.30
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace D4T;

use \D4T\Configuration;
use \D4T\ApiException;
use \D4T\ObjectSerializer;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  D4T
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for updateUser
     *
     * Update user.
     *
     */
    public function testUpdateUser()
    {
    }

    /**
     * Test case for userAddPost
     *
     * Create user.
     *
     */
    public function testUserAddPost()
    {
    }

    /**
     * Test case for userDepositPost
     *
     * Deposit account.
     *
     */
    public function testUserDepositPost()
    {
    }

    /**
     * Test case for userResetPwdPost
     *
     * Reset password.
     *
     */
    public function testUserResetPwdPost()
    {
    }

    /**
     * Test case for userUserLoginGet
     *
     * Get user by user login.
     *
     */
    public function testUserUserLoginGet()
    {
    }

    /**
     * Test case for userWithdrawPost
     *
     * Withdraw account.
     *
     */
    public function testUserWithdrawPost()
    {
    }

    /**
     * Test case for usersBulkAddPost
     *
     * Create users.
     *
     */
    public function testUsersBulkAddPost()
    {
    }

    /**
     * Test case for usersBulkBalancePost
     *
     * bulk balance.
     *
     */
    public function testUsersBulkBalancePost()
    {
    }

    /**
     * Test case for usersBulkUpdatePost
     *
     * bulk update.
     *
     */
    public function testUsersBulkUpdatePost()
    {
    }

    /**
     * Test case for usersBulkWithdrawPost
     *
     * bulk withdraw.
     *
     */
    public function testUsersBulkWithdrawPost()
    {
    }

    /**
     * Test case for usersGroupGet
     *
     * Get list of users.
     *
     */
    public function testUsersGroupGet()
    {
    }

    /**
     * Test case for usersUploadPost
     *
     * Upload account in csv.
     *
     */
    public function testUsersUploadPost()
    {
    }
}
